description: "This reasearch project develop training materials for researchers wanting to learn to build project websites in GitHub with GitHub Pages"
email: "team@carpentries.org"
github: "https://github.com/swcarpentry"
